### ISSUE TITLE
Permission sought from recompileorg - Permission to add FreeChaf to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by inactive123** [libretro/FreeChaF#5]
Hi there @recompileorg,

we would like to seek your permission to include FreeChaf as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by recompileorg** [comment]
I don't see anything wrong with it off-hand.  As long as the user knows where to get the source and license, it should be in compliance with the GPLv3.   Am I missing something important?

**Comment by inactive123** [comment]
Nope, that is all there is to it. We just wanted to be respectful about it and to let the authors make t he final call.

So given this, we can assume both freechaf and freeintv approved?

**Comment by recompileorg** [comment]
I'd say so.  Consider my approval for both given.

**Comment by LibretroAdmin** [comment]
@recompileorg It took a while, but it has finally been added!

https://store.steampowered.com/app/1227458/RetroArch__FreeChaF/

FreeIntv is next.

**Comment by recompileorg** [comment]
Neat!  Thanks for letting me know.
